tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DBT_PROJECTS_TRANSFORMER
      database: DBT_PROJECTS_PROD
      schema: ANALYTICS
      warehouse: DBT_PROJECTS_TRANSFORMING
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DBT_PROJECTS_TRANSFORMER
      database: DBT_PROJECTS_PROD
      schema: ANALYTICS
      warehouse: DBT_PROJECTS_TRANSFORMING